//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.App.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToe.App.Localization.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator:.
        /// </summary>
        public static string GamePart_Creator {
            get {
                return ResourceManager.GetString("GamePart_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Opponent Name.
        /// </summary>
        public static string GamePart_ExternalOpp {
            get {
                return ResourceManager.GetString("GamePart_ExternalOpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Opponent? Enter Name: .
        /// </summary>
        public static string GamePart_OpponentName {
            get {
                return ResourceManager.GetString("GamePart_OpponentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is your Opponent?.
        /// </summary>
        public static string GamePart_OpponentWho {
            get {
                return ResourceManager.GetString("GamePart_OpponentWho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string GamePart_Start {
            get {
                return ResourceManager.GetString("GamePart_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the game.
        /// </summary>
        public static string GamePart_StartTip {
            get {
                return ResourceManager.GetString("GamePart_StartTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Setup.
        /// </summary>
        public static string GamePart_Title {
            get {
                return ResourceManager.GetString("GamePart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X - goes first, O - goes second.
        /// </summary>
        public static string GamePart_ToggleTip {
            get {
                return ResourceManager.GetString("GamePart_ToggleTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Player: .
        /// </summary>
        public static string Gameplay_Player {
            get {
                return ResourceManager.GetString("Gameplay_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the Game.
        /// </summary>
        public static string Gameplay_Restart {
            get {
                return ResourceManager.GetString("Gameplay_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        public static string Gameplay_Surr {
            get {
                return ResourceManager.GetString("Gameplay_Surr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn: .
        /// </summary>
        public static string Gameplay_Turn {
            get {
                return ResourceManager.GetString("Gameplay_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Difficulty:.
        /// </summary>
        public static string GameSetup_AI {
            get {
                return ResourceManager.GetString("GameSetup_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EASY.
        /// </summary>
        public static string GameSetup_AI_Easy {
            get {
                return ResourceManager.GetString("GameSetup_AI_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HARD.
        /// </summary>
        public static string GameSetup_AI_Hard {
            get {
                return ResourceManager.GetString("GameSetup_AI_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDIUM.
        /// </summary>
        public static string GameSetup_AI_Med {
            get {
                return ResourceManager.GetString("GameSetup_AI_Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Size:.
        /// </summary>
        public static string GameSetup_BoardSize {
            get {
                return ResourceManager.GetString("GameSetup_BoardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: .
        /// </summary>
        public static string GameSetup_BoardSizeValue {
            get {
                return ResourceManager.GetString("GameSetup_BoardSizeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string GameSetup_CreateGame {
            get {
                return ResourceManager.GetString("GameSetup_CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new game.
        /// </summary>
        public static string GameSetup_CreateGame_ToolTip {
            get {
                return ResourceManager.GetString("GameSetup_CreateGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Mode:.
        /// </summary>
        public static string GameSetup_Mode {
            get {
                return ResourceManager.GetString("GameSetup_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        public static string GameSetup_Mode_Multi {
            get {
                return ResourceManager.GetString("GameSetup_Mode_Multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        public static string GameSetup_Mode_Solo {
            get {
                return ResourceManager.GetString("GameSetup_Mode_Solo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Setup.
        /// </summary>
        public static string GameSetup_Title {
            get {
                return ResourceManager.GetString("GameSetup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string Home_Hello {
            get {
                return ResourceManager.GetString("Home_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Home_Name {
            get {
                return ResourceManager.GetString("Home_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Here?.
        /// </summary>
        public static string Home_New {
            get {
                return ResourceManager.GetString("Home_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Home_Pwd {
            get {
                return ResourceManager.GetString("Home_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string Home_PwdConf {
            get {
                return ResourceManager.GetString("Home_PwdConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Home_SignIn {
            get {
                return ResourceManager.GetString("Home_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Home_SignUp {
            get {
                return ResourceManager.GetString("Home_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic Tac Toe.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are You?.
        /// </summary>
        public static string Home_Who {
            get {
                return ResourceManager.GetString("Home_Who", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Nav_Exit {
            get {
                return ResourceManager.GetString("Nav_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Nav_Game {
            get {
                return ResourceManager.GetString("Nav_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string Nav_Profile {
            get {
                return ResourceManager.GetString("Nav_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string Nav_Stats {
            get {
                return ResourceManager.GetString("Nav_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Profile_ChangePwd {
            get {
                return ResourceManager.GetString("Profile_ChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Profile_NewPwd {
            get {
                return ResourceManager.GetString("Profile_NewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password confirmation.
        /// </summary>
        public static string Profile_NewPwdConf {
            get {
                return ResourceManager.GetString("Profile_NewPwdConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string Profile_OldPwd {
            get {
                return ResourceManager.GetString("Profile_OldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change.
        /// </summary>
        public static string Profile_PwdChangeTitle {
            get {
                return ResourceManager.GetString("Profile_PwdChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User:.
        /// </summary>
        public static string Profile_User {
            get {
                return ResourceManager.GetString("Profile_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Played.
        /// </summary>
        public static string Stats_GamesPlayed {
            get {
                return ResourceManager.GetString("Stats_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Type.
        /// </summary>
        public static string Stats_GameType {
            get {
                return ResourceManager.GetString("Stats_GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Games.
        /// </summary>
        public static string Stats_Header_LongGames {
            get {
                return ResourceManager.GetString("Stats_Header_LongGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Games.
        /// </summary>
        public static string Stats_Header_MostGames {
            get {
                return ResourceManager.GetString("Stats_Header_MostGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Win Ratio.
        /// </summary>
        public static string Stats_Header_WinRate {
            get {
                return ResourceManager.GetString("Stats_Header_WinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Stats_Opponent {
            get {
                return ResourceManager.GetString("Stats_Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Stats_Title {
            get {
                return ResourceManager.GetString("Stats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns.
        /// </summary>
        public static string Stats_Turns {
            get {
                return ResourceManager.GetString("Stats_Turns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Stats_User {
            get {
                return ResourceManager.GetString("Stats_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win Ratio.
        /// </summary>
        public static string Stats_WinRatio {
            get {
                return ResourceManager.GetString("Stats_WinRatio", resourceCulture);
            }
        }
    }
}
